server:
  port: 8081

diy:
  elasticsearch:
    cluster-name: momoes
    host: 192.168.157.64
    port: 9200
    uniqueConnectTimeConfig: true
    uniqueConnectNumConfig: true
    schema: http
    connectTimeOut: 30000
    socketTimeOut: 30000
    connectionRequestTimeOut: 5000
    maxConnectNum: 100
    maxConnectPerRoute: 100